### ISSUE TITLE
Relicense under MIT

### ISSUE THREAD

**Issue by ubsan** [leios/algorithm-archive#20]
ping:

- [x] @ubsan

- [x] @leios 

- [x] @Gathros 

- [x] @KingFredrickVI 

- [x] @julianschacherpp 

Please write the following in a comment

> I agree to have all of my previous and future commits to this repository licensed under the MIT license, as found in LICENSE.md.

and put your name in the CONTRIBUTING.md file.

me first:

I agree to have all of my previous and future commits to this repository licensed under the MIT license, as found in LICENSE.md.

**Comment by leios** [comment]
I agree to have all of my previous and future commits to this repository licensed under the MIT 2-clause license, as found in LICENSE.md.

Also: You are super quick.

**Comment by ubsan** [comment]
yes, yes I am.

**Comment by Butt4cak3** [comment]
I agree to have all of my previous and future commits to this repository licensed under the unlicense, as found in LICENSE.md.

**Comment by ubsan** [comment]
Apparently, we should not be using the unlicense.

**Comment by leios** [comment]
Yeah, sorry @Butt4cak3, mind writing "MIT license" instead of "unlicense"?

**Comment by Gathros** [comment]
I agree to have all of my previous and future commits to this repository licensed under the MIT license, as found in LICENSE.md.

**Comment by julianschacherpp** [comment]
I agree to have all of my previous and future commits to this repository licensed under the MIT license, as found in LICENSE.md.

**Comment by KingFredrickVI** [comment]
I agree to have all of my previous and future commits to this repository licensed under the MIT license, as found in LICENSE.md.

**Comment by leios** [comment]
Great! Everyone answered. I'll update everything soon!
