### ISSUE TITLE
Code box is too small

### ISSUE THREAD

**Issue by jiegillet** [leios/algorithm-archive#41]
I think the way code is displayed should be changed a bit. Right now it's only about 45 characters wide. Ideally it should be 80.
<img width="472" alt="screen shot 2018-02-08 at 12 18 06" src="https://user-images.githubusercontent.com/16929078/35953882-242a2c2e-0cca-11e8-9c6c-c504de3e17d3.png">

**Comment by leios** [comment]
I am not sure how easy this is to fix using the importcodeblock plugin (or whatever it is called); however, if you click the button on the upper left, it will expand out the view to the rest of the page.

![screenshot](https://user-images.githubusercontent.com/4985692/35955000-26c2bb62-0cd0-11e8-9185-85b23953d858.jpg)

**Comment by jiegillet** [comment]
That's better than nothing ^^

**Comment by leios** [comment]
There must be a way to do this with the plug-in. I'll look into it soon. Thanks!

**Comment by julianschacherpp** [comment]
Ok, I just looked at our files and the theme-api documentation. The split-view option is the default and I also enabled it in the book.json for no logical reasons... So I created a PR fixing that. https://github.com/leios/algorithm-archive/pull/42

**Comment by julianschacherpp** [comment]
Thank you @jiegillet for pointing that out :)

**Comment by leios** [comment]
Pull request merged. I think the issue is resolved for now.

**Comment by jiegillet** [comment]
default split is back from one of the recent commits!

**Comment by leios** [comment]
Ah, I think I know which one. I'll fix it.

**Comment by julianschacherpp** [comment]
I think split isn't back. I just checked with a guest session on chrome and the code took up the full width. Can you maybe check the AAA with another browser that has no cookies or anything stored? @jiegillet

**Comment by jiegillet** [comment]
My bad, sorry! I checked with 2 browsers, but then cleared cache on one and you're right.

**Comment by julianschacherpp** [comment]
@jiegillet no problem :)

**Comment by julianschacherpp** [comment]
It was also because of the cache, that I thought for a long time, that split-view is disabled by default (when it wasn't). You pointed it out then. :)
