### ISSUE TITLE
Would you be willing to let me rewrite the C++ section in `euclidean`?

### ISSUE THREAD

**Issue by ubsan** [leios/algorithm-archive#9]
I'd like to change the style a bit to make it more similar to standard C++.

Also, the giant banner is unnecessary, and poor for accessibility.

**Comment by ubsan** [comment]
(It's fine if you don't want to allow me to. please allow me to remove the banner tho...)

**Comment by julianschacherpp** [comment]
You could edit the file and open a pull request. Then it's getting merged, if the implementation is better. Also you can edit the files while you're discussing the implementation detail.

**Comment by leios** [comment]
Yeah, it's fine to update the C++ code, no problem. This week, I want to take all the code and put it in separate, compilable files so I wanted the banner (or at the very least a comment) so it could have compile instructions in it.

I definitely don't mind people re-writing code if it makes it cleaner and easier to understand.

**Comment by ubsan** [comment]
cool :)

Opened an issue at #13 for discussion on compilation flags, and opened a PR at #12
